# Generated by Django 4.0.4 on 2022-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('bio', models.TextField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=22, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('acc_type', models.CharField(default='user', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
