# Generated by Django 4.0.4 on 2022-05-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_module_perms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_perm',
            field=models.BooleanField(default=True),
        ),
    ]
