# Generated by Django 4.0.4 on 2022-05-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_alter_user_has_module_perms_alter_user_has_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_module_perms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_perm',
        ),
    ]
