# Generated by Django 4.0.4 on 2022-05-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('mover_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=99)),
                ('to_location', models.CharField(max_length=99)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('mover_id', models.IntegerField()),
                ('fees', models.IntegerField(default=5000)),
                ('is_accepted', models.BooleanField(default=False)),
                ('inventory', models.CharField(max_length=500)),
                ('moving_time', models.CharField(max_length=66)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
